name: module3_task1
run-name: module3_task1
on: # yamllint disable-line rule:truthy
  push:
  schedule:
    - cron: "0 1 * * *"
jobs:
  Add-Build-Dependencies:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        run: ./setup.sh
        working-directory: module3_task1

      - name: Build
        run: sudo make build
        working-directory: module3_task1
